steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/peri/peri-image:latest'
  - '.'

images:
- 'gcr.io/peri/peri-image:latest'

serviceAccount: 'gcloudac@cfv2024.iam.gserviceaccount.com'

logging:
  loggingOptions:
    logging: REGIONAL_USER_OWNED_BUCKET
