steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/peri/peri-image:latest'
  - '.'
  logging: LEGACY

images:
- 'gcr.io/peri/peri-image:latest'

serviceAccount:
  email: 'gcloudac@cfv2024.iam.gserviceaccount.com'
